### ISSUE TITLE
will this work with a MAX17050?

### ISSUE THREAD

**Issue by hannescam** [sparkfun/SparkFun_MAX1704x_Fuel_Gauge_Arduino_Library#12]

**Comment by PaulZC** [comment]
Hi @hannescam ,

Maybe?

I suggest you compare the data sheets for the 17048 and 17050. If the I2C registers look the same, then it might work.

Why not give it a try?

Best wishes,
Paul

**Comment by hannescam** [comment]
i cant just give it a try i am trying to remake on in softwae on another mcu and using this library to test my code

**Comment by hannescam** [comment]
@PaulZC it is completley different from the i2c registers so incompatible and it has way more features
