### ISSUE TITLE
is it possible to make this code work for a MAX17050?

### ISSUE THREAD

**Issue by hannescam** [sparkfun/SparkFun_MAX1704x_Fuel_Gauge_Arduino_Library#13]
i want to make a MAX17050 emulator for the samd21 and want to test it using the esp32 with this library
the i2c registers arent the same between the supported chips and the MAX17050
please dont close this issue
thankyou

**Comment by PaulZC** [comment]
Hi @hannescam ,

As far as I can tell, this issue has nothing to do with _this_ library?

Closing.

Paul
