### ISSUE TITLE
How to detect if a battery is charging? (MAX17048)

### ISSUE THREAD

**Issue by gvitali** [sparkfun/SparkFun_MAX1704x_Fuel_Gauge_Arduino_Library#16]
What is correct way to detect if a battery is charging (to show charging animation)?
I tried to use `getChangeRate()`, but it has lag too often (up to a minute).
I tried to use `getVoltage()`, but it has values are same both for charging and discharging.
Could you please suggest a solution?

ESP32-S3, MAX17048

**Comment by PaulZC** [comment]
Hi @gvitali ,

It would be better to get this from your charger IC.

I hope this helps,
Paul
