### ISSUE TITLE
No need to wait after Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [sparkfun/SparkFun_MAX1704x_Fuel_Gauge_Arduino_Library#2]
In the file "SparkFun_MAX1704x_Fuel_Gauge_Arduino_Library.cpp" there is waiting with a timeout after the Wire.requestFrom(). That while-statement with the delay may be removed. There is no such thing as waiting after a Wire.requestFrom().

Explanation: [Common-mistakes#1](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#1)

**Comment by PaulZC** [comment]
Thank you @Koepel ,
Changed in [this commit](https://github.com/sparkfun/SparkFun_MAX1704x_Fuel_Gauge_Arduino_Library/commit/6e2f3c7865bf3a0a5b4c9b86be5a3dcdcea3702b). I will include the changes in the next release after testing. Hopefully we won't see another case of [this issue](https://github.com/sparkfun/SparkFun_BNO080_Arduino_Library/issues/3).
Best wishes,
Paul

**Comment by PaulZC** [comment]
Apologies for the delay! Resolved in v1.0.2...
